on: [push, pull_request]
name: Test
jobs:
  full:
    strategy:
      matrix:
        go-version:
          - '1.25'
        platform:
          # Would like to test mac & win but not sure how to install opus on
          # those in GH actions, yet.
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install system dependencies
      run: sudo apt-get install pkg-config libopus-dev libopusfile-dev moreutils
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -race -v ./...

  embedlibopusfile:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    - name: Install system dependencies
      run: sudo apt-get install pkg-config libopus-dev
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -race -v ./...